//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyQuizMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_answers
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public string answer { get; set; }
        public Nullable<int> is_correct { get; set; }
    }
}
