//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyQuizMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class questions
    {
        public int id { get; set; }
        public int quiz_id { get; set; }
        public string question { get; set; }
        public Nullable<bool> question_difficulty { get; set; }
        public Nullable<bool> multianswer { get; set; }
    }
}
