//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyQuizMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_statistics
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int question_id { get; set; }
        public Nullable<int> correct_answers { get; set; }
        public Nullable<int> incorrect_answers { get; set; }
    }
}
